# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Karen Chui
email: oliver@stenbom.eu
description: > # this means to ignore newlines until "baseurl:"
  Photographer, DJ and entrepreneur. Born in Canada but raised mainly in Hong Kong, currently studying in Birmingham. I have always found myself drawn to exploring the wonders that the visual and musical arts have to offer. This page is simply a portfolio of my work so that it doesn't remain hidden on a laptop drive somewhere.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://karenchui.co.uk" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
